version: "3"
services:
  checkout:
    build: .
    depends_on:
      - db
    ports:
      - '3003:3003'
  db:
    image: mysql:5.7
    restart: always
    expose:
      - '3006'
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'checkout'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
